In [1]:
## First up is create some data

In [35]:
from random import choice
import matplotlib.pyplot as plt
import numpy as np
# Define the number of samples 
num_samples = 4000
n = 3

In [36]:
from scipy.stats import ortho_group

In [37]:
D  = ortho_group.rvs(dim = n)
print np.linalg.det(D)
np.dot(D[1,:], D[1,:])

1.0


1.0000000000000002

In [38]:
import random
# Create a random Matrix
A = np.matrix( np.random.rand(n,n))

In [39]:
## Using the last two values which aimed at creating an orthonormal 
## basis and a set of eigen values, we create a matrix

In [43]:
SymA = np.dot(A, np.transpose(A))
C = SymA+ n*np.eye(n)

In [44]:
print np.linalg.det(SymA+ n*np.eye(n))

55.1376796583


In [45]:
np.linalg.eig(C)[0]

array([ 5.22376329,  3.02271719,  3.4919457 ])

In [47]:
print C

[[ 3.62076557  0.60804936  0.59023409]
 [ 0.60804936  3.64152212  0.62272139]
 [ 0.59023409  0.62272139  4.47613848]]


In [50]:
mean = [np.random.rand()*20 for i in xrange(n)]

In [51]:
print mean

[10.496293268292348, 14.245538246245125, 6.557123686999682]


In [52]:
## Next Go ahead and get some data 

In [ ]:
# Correlation matrix is singular when the number of 
# attributes are equal to or less than the number of
# samples present.


import random
import matplotlib.pyplot as plt

# Choose size of the matrices
n = 100

# Create a random Matrix
A = np.matrix( np.random.rand(n,n))

## Using the last two values which aimed at creating an orthonormal 
## basis and a set of eigen values, we create a matrix
SymA = np.dot(A, np.transpose(A))
C = SymA+ n*np.eye(n)
mean = [np.random.rand()*20 for i in xrange(n)]

# Now get the data samples
NUM_SAMPLES =20
T = []
for i in xrange(20000, 0, -20):
    X = np.random.multivariate_normal(mean, C, i)
    C_ESTIMATE = np.cov(np.transpose(X))
    T.append(np.linalg.det(C_ESTIMATE))
plt.hist(T)
plt.show()

array([[ 3.42736436,  0.65724934,  0.55102204],
       [ 0.65724934,  3.75077449,  0.55380286],
       [ 0.55102204,  0.55380286,  4.30675269]])